apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
  name: kustomize-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: Kustomize/overlays/dev
    repoURL: 'git@github.com:nunucloud/sre-test.git'
    targetRevision: main
    directory:
      recurse: true

  project: default
  syncPolicy:
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 1m0s
        factor: 2
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Replace=false