apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: tb
  namespace: tekton-test
spec:
  params:
  - name: imagetag
    value: $(body.head_commit.id)
  - name: giturl
    value: $(body.repository.url)