apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-sa
  namespace: tekton-test
secrets:
  - name: git-credential
  - name: docker-credentials
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: '*'
  name: role-for-tektondeploy
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebind-for-deploy
subjects:
  - kind: ServiceAccount
    name: cicd
    namespace: tekton-test
roleRef:
  kind: ClusterRole
  name: role-for-tektondeploy
  apiGroup: rbac.authorization.k8s.io
