apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
  namespace: tekton-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario
        image: changetagname 
---
apiVersion: v1
kind: Service
metadata:
  name: mario
  namespace: tekton-test
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /mario/index.html
spec:
  selector:
    app: mario
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30008
  type: NodePort
